# Generated by Django 6.0.1 on 2026-08-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadattempt",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
