# Generated by Django 6.0.1 on 2026-08-29 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "platform_target",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("format", models.CharField(blank=True, default="", max_length=64)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Researching", "Researching"),
                            ("Research Approved", "Research Approved"),
                            ("Scripting", "Scripting"),
                            ("Script Approved", "Script Approved"),
                            ("Producing", "Producing"),
                            ("Video Approved", "Video Approved"),
                            ("Scheduled", "Scheduled"),
                            ("Published", "Published"),
                            ("Archived", "Archived"),
                        ],
                        default="Draft",
                        max_length=32,
                    ),
                ),
                ("is_template", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["team"], name="projects_pr_team_id_1e35fa_idx"
                    ),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="projects_pr_lifecyc_a6aaa2_idx",
                    ),
                ],
            },
        ),
    ]
