# Generated by Django 6.0.1 on 2026-08-30 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        ("script", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("characters", models.JSONField(blank=True, default=list)),
                (
                    "gate_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("approval_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_set",
                        to="projects.project",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Script this set was detected from (Gate 2).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_sets",
                        to="script.script",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_sets",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "gate_state"],
                        name="character_c_team_id_7c6b9e_idx",
                    ),
                    models.Index(
                        fields=["project", "gate_state"],
                        name="character_c_project_c1dfa7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("age", models.CharField(blank=True, default="", max_length=64)),
                ("gender", models.CharField(blank=True, default="", max_length=64)),
                ("appearance", models.JSONField(blank=True, default=dict)),
                ("clothing", models.JSONField(blank=True, default=dict)),
                ("accessories", models.JSONField(blank=True, default=list)),
                ("style", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project where this character was first detected.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_library",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["character_id", "-version"],
                "indexes": [
                    models.Index(
                        fields=["team", "character_id"],
                        name="character_c_team_id_62b0a9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "character_id", "version"),
                        name="unique_library_character_version",
                    )
                ],
            },
        ),
    ]
