# Generated by Django 6.0.1 on 2026-08-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("raw_output", models.JSONField(blank=True, default=dict)),
                (
                    "gate_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("approval_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_research",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gap_type",
                    models.CharField(
                        choices=[("gap", "Gap"), ("contradiction", "Contradiction")],
                        default="gap",
                        max_length=24,
                    ),
                ),
                ("description", models.TextField()),
                ("source_a", models.TextField(blank=True, default="")),
                ("source_b", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gaps",
                        to="research.research",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("snippet", models.TextField(blank=True, default="")),
                ("credibility_score", models.FloatField(default=0.0)),
                ("accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="research.research",
                    ),
                ),
            ],
            options={
                "ordering": ["-credibility_score", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="research",
            index=models.Index(
                fields=["team", "gate_state"], name="research_re_team_id_a95ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="research",
            index=models.Index(
                fields=["project", "gate_state"], name="research_re_project_2624fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchgap",
            index=models.Index(
                fields=["research", "gap_type"], name="research_re_researc_b79c59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchsource",
            index=models.Index(
                fields=["research"], name="research_re_researc_6c45a1_idx"
            ),
        ),
    ]
