# Generated by Django 6.0.1 on 2026-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("status", "status"),
                    ("approval_request", "approval_request"),
                    ("reminder", "reminder"),
                    ("publish_outcome", "publish_outcome"),
                    ("publish_failure", "publish_failure"),
                    ("team_assignment", "team_assignment"),
                ],
                max_length=32,
            ),
        ),
    ]
