# Generated by Django 6.0.1 on 2026-08-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        ("scene", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_id", models.CharField(max_length=64)),
                ("scene_order", models.PositiveIntegerField(default=0)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("voice", "Voice / Narration"),
                            ("music", "Music / Audio"),
                            ("subtitle", "Subtitle / Caption"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("asset_ref", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("direction", models.TextField(blank=True, default="")),
                ("narration", models.TextField(blank=True, default="")),
                ("characters", models.JSONField(blank=True, default=list)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("pacing", models.CharField(blank=True, default="", max_length=32)),
                ("transition", models.CharField(blank=True, default="", max_length=32)),
                ("voice", models.JSONField(blank=True, default=dict)),
                ("music", models.JSONField(blank=True, default=dict)),
                ("caption", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_media",
                        to="projects.project",
                    ),
                ),
                (
                    "scene_builder",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Scene Builder package this media derives from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media",
                        to="scene.scenebuilder",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Bound to the project's team; every query is team-scoped.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_media",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["scene_order", "media_type"],
                "indexes": [
                    models.Index(
                        fields=["team", "status"], name="scene_media_team_id_e0c6f3_idx"
                    ),
                    models.Index(
                        fields=["project", "media_type"],
                        name="scene_media_project_4c107d_idx",
                    ),
                    models.Index(
                        fields=["scene_builder", "scene_id"],
                        name="scene_media_scene_b_b85283_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene_builder", "scene_id", "media_type"),
                        name="uniq_scene_media_builder_scene_type",
                    )
                ],
            },
        ),
    ]
