# Generated by Django 6.0.1 on 2026-08-31 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        ("scene", "0001_initial"),
        ("video", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_target",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "aspect_ratio",
                    models.CharField(blank=True, default="16:9", max_length=16),
                ),
                ("resolution_width", models.PositiveIntegerField(default=1920)),
                ("resolution_height", models.PositiveIntegerField(default=1080)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rendering", "Rendering"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "asset_ref",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reference to the rendered preview asset.",
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("scene_count", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Whether the preview has been reviewed and approved.",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_previews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previews",
                        to="projects.project",
                    ),
                ),
                (
                    "scene_builder",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Scene Builder package this preview derives from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="previews",
                        to="scene.scenebuilder",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previews",
                        to="accounts.team",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        help_text="The VideoAsset this preview is derived from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previews",
                        to="video.videoasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "status"], name="preview_pre_team_id_923209_idx"
                    ),
                    models.Index(
                        fields=["project", "approval_state"],
                        name="preview_pre_project_ee420a_idx",
                    ),
                    models.Index(
                        fields=["approval_state", "platform_target"],
                        name="preview_pre_approva_0781ae_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "platform_target"),
                        name="uniq_preview_project_platform",
                    )
                ],
            },
        ),
    ]
