# Generated by Django 6.0.1 on 2026-08-31 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        ("scene", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_target",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "aspect_ratio",
                    models.CharField(blank=True, default="9:16", max_length=16),
                ),
                ("resolution_width", models.PositiveIntegerField(default=1080)),
                ("resolution_height", models.PositiveIntegerField(default=1920)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("asset_ref", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("scene_count", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("error_message", models.TextField(blank=True, default="")),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="projects.project",
                    ),
                ),
                (
                    "scene_builder",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Scene Builder package this video derives from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videos",
                        to="scene.scenebuilder",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "status"], name="video_video_team_id_9430a6_idx"
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="video_video_project_f9fd76_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "platform_target"),
                        name="uniq_video_project_platform",
                    )
                ],
            },
        ),
    ]
