# Generated by Django 6.0.1 on 2026-08-31 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="Target platform (YouTube, TikTok, Instagram, etc.)",
                        max_length=64,
                    ),
                ),
                (
                    "scheduled_local_datetime",
                    models.DateTimeField(
                        help_text="User-requested local date/time for publication."
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone identifier (e.g. Asia/Kolkata, America/New_York).",
                        max_length=64,
                    ),
                ),
                (
                    "scheduled_utc_datetime",
                    models.DateTimeField(
                        help_text="Normalized UTC datetime for scheduling."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("rescheduled", "Rescheduled"),
                            ("cancelled", "Cancelled"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "best_time_suggestion",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Deterministic best-time suggestion for this platform.",
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the pre-publish reminder has been sent.",
                    ),
                ),
                (
                    "reminder_scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the reminder should fire.",
                        null=True,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "previous_scheduled_utc",
                    models.DateTimeField(
                        blank=True,
                        help_text="Previous UTC time before reschedule.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_utc_datetime"],
                "indexes": [
                    models.Index(
                        fields=["team", "status"], name="scheduler_s_team_id_e68b15_idx"
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="scheduler_s_project_c21aaa_idx",
                    ),
                    models.Index(
                        fields=["scheduled_utc_datetime", "status"],
                        name="scheduler_s_schedul_4382cb_idx",
                    ),
                    models.Index(
                        fields=["status", "reminder_sent"],
                        name="scheduler_s_status_5c53cc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "platform"),
                        name="uniq_schedule_project_platform",
                    )
                ],
            },
        ),
    ]
