# Generated by Django 6.0.1 on 2026-08-30 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("ai_orchestration", "0001_initial"),
        ("projects", "0001_initial"),
        ("scene", "0001_initial"),
        ("scene_media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegenerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The stable scene id to regenerate (empty only for full).",
                        max_length=64,
                    ),
                ),
                ("media_types", models.JSONField(blank=True, default=list)),
                (
                    "full",
                    models.BooleanField(
                        default=False,
                        help_text="True only when the user explicitly requests full regeneration.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("media_snapshot_version", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "async_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regeneration_requests",
                        to="ai_orchestration.asyncjob",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who requested the regeneration.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeneration_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeneration_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "scene_builder",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Scene Builder package (Gate 4) being edited.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regeneration_requests",
                        to="scene.scenebuilder",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Bound to the project's team; every query is team-scoped.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeneration_requests",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SceneMediaVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="The media version number this snapshot represents."
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("voice", "Voice / Narration"),
                            ("music", "Music / Audio"),
                            ("subtitle", "Subtitle / Caption"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scene_id", models.CharField(max_length=64)),
                ("scene_order", models.PositiveIntegerField(default=0)),
                ("asset_ref", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("direction", models.TextField(blank=True, default="")),
                ("narration", models.TextField(blank=True, default="")),
                ("characters", models.JSONField(blank=True, default=list)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("pacing", models.CharField(blank=True, default="", max_length=32)),
                ("transition", models.CharField(blank=True, default="", max_length=32)),
                ("voice", models.JSONField(blank=True, default=dict)),
                ("music", models.JSONField(blank=True, default=dict)),
                ("caption", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="scene_media.scenemedia",
                    ),
                ),
                (
                    "regeneration",
                    models.ForeignKey(
                        blank=True,
                        help_text="The regeneration run that produced this snapshot.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="regeneration.regenerationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["media", "-version"],
            },
        ),
        migrations.AddIndex(
            model_name="regenerationrequest",
            index=models.Index(
                fields=["team", "status"], name="regeneratio_team_id_747de1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regenerationrequest",
            index=models.Index(
                fields=["project", "status"], name="regeneratio_project_297809_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regenerationrequest",
            index=models.Index(
                fields=["scene_builder", "scene_id"],
                name="regeneratio_scene_b_7213ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scenemediaversion",
            index=models.Index(
                fields=["media", "version"], name="regeneratio_media_i_b5e498_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scenemediaversion",
            index=models.Index(
                fields=["scene_id", "media_type"], name="regeneratio_scene_i_b97934_idx"
            ),
        ),
    ]
