# Generated by Django 6.0.1 on 2026-08-31 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        ("scene", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbnailAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_target",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("width", models.PositiveIntegerField(default=1280)),
                ("height", models.PositiveIntegerField(default=720)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("asset_ref", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "title_text",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("variations", models.JSONField(blank=True, default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="projects.project",
                    ),
                ),
                (
                    "scene_builder",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Scene Builder package this thumbnail derives from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thumbnails",
                        to="scene.scenebuilder",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "status"], name="thumbnail_t_team_id_3d6757_idx"
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="thumbnail_t_project_0f675c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "platform_target"),
                        name="uniq_thumbnail_project_platform",
                    )
                ],
            },
        ),
    ]
