# Generated by Django 6.0.1 on 2026-08-30 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("research_generation", "Research Generation"),
                            ("script_generation", "Script Generation"),
                            ("character_detection", "Character Detection"),
                            ("scene_media_generation", "Scene Media Generation"),
                            ("regeneration", "Scene Regeneration"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("cost_currency", models.CharField(default="USD", max_length=3)),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "status"], name="ai_orchestr_team_id_8a041d_idx"
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="ai_orchestr_project_c2f32a_idx",
                    ),
                    models.Index(
                        fields=["job_type", "status"],
                        name="ai_orchestr_job_typ_6d348c_idx",
                    ),
                ],
            },
        ),
    ]
