# Generated by Django 6.0.1 on 2026-08-30 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("character", "0001_initial"),
        ("projects", "0001_initial"),
        ("script", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenes", models.JSONField(blank=True, default=list)),
                (
                    "gate_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("approval_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scene_builders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Character set (Gate 3) whose characters are assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_builders",
                        to="character.character",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_builder",
                        to="projects.project",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        blank=True,
                        help_text="The approved Script package (Gate 2) this scene package maps.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_builders",
                        to="script.script",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_builders",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "gate_state"],
                        name="scene_scene_team_id_190695_idx",
                    ),
                    models.Index(
                        fields=["project", "gate_state"],
                        name="scene_scene_project_fea053_idx",
                    ),
                ],
            },
        ),
    ]
